<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    
    public function run(): void
    {
        $users = [
            [
                'name' => 'سارة محمد',
                'email' => 'sara@example.com',
                'password' => Hash::make('password123'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'حرفية متخصصة في صناعة المجوهرات اليدوية من الفضة والأحجار الكريمة',
                'created_at' => '2023-01-15',
                'last_login' => '2023-09-20',
                'phone' => '+20123456789',
                'location' => 'القاهرة، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'محمد أحمد',
                'email' => 'mohammed@example.com',
                'password' => Hash::make('password123'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'حرفي متخصص في النحت على الخشب وصناعة الأثاث اليدوي التقليدي',
                'created_at' => '2023-02-22',
                'last_login' => '2023-09-18',
                'phone' => '+20123456790',
                'location' => 'الإسكندرية، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'نورا علي',
                'email' => 'nora@example.com',
                'password' => Hash::make('password123'),
                'role' => 'buyer',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-03-10',
                'last_login' => '2023-09-15',
                'phone' => '+9627777777',
                'location' => 'عمان، الأردن',
                'active_role' => 'buyer',
            ],
            [
                'name' => 'أحمد محمود',
                'email' => 'ahmed@example.com',
                'password' => Hash::make('password123'),
                'role' => 'buyer',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-04-05',
                'last_login' => '2023-09-10',
                'phone' => '+9715555555',
                'location' => 'دبي، الإمارات',
                'active_role' => 'buyer',
            ],
            [
                'name' => 'مدير النظام',
                'email' => 'admin@example.com',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-01-01',
                'last_login' => '2023-09-21',
                'phone' => '+20100000001',
                'location' => 'القاهرة، مصر',
                'active_role' => 'admin',
            ],
            [
                'name' => 'فاطمة خالد',
                'email' => 'fatima.seller@example.com',
                'password' => Hash::make('sellerpass1'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'متخصصة في صناعة المنسوجات اليدوية والتطريز التقليدي',
                'created_at' => '2023-05-10',
                'last_login' => '2023-09-19',
                'phone' => '+966500000001',
                'location' => 'الرياض، السعودية',
                'active_role' => 'seller',
            ],
            [
                'name' => 'علي حسن',
                'email' => 'ali.seller@example.com',
                'password' => Hash::make('sellerpass2'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'حرفي متخصص في صناعة الفخار والخزف التقليدي',
                'created_at' => '2023-06-15',
                'last_login' => '2023-09-17',
                'phone' => '+96590000001',
                'location' => 'الكويت العاصمة، الكويت',
                'active_role' => 'seller',
            ],
            [
                'name' => 'ليلى إبراهيم',
                'email' => 'layla.seller@example.com',
                'password' => Hash::make('sellerpass3'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'pending',
                'created_at' => '2023-07-20',
                'last_login' => null,
                'phone' => '+97430000001',
                'location' => 'الدوحة، قطر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'خالد عبدالله',
                'email' => 'khaled.seller@example.com',
                'password' => Hash::make('sellerpass4'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-08-25',
                'last_login' => '2023-09-16',
                'phone' => '+97330000002',
                'location' => 'المنامة، البحرين',
                'active_role' => 'seller',
            ],
            [
                'name' => 'مريم سعيد',
                'email' => 'mariam.seller@example.com',
                'password' => Hash::make('sellerpass5'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-09-01',
                'last_login' => null,
                'phone' => '+96890000003',
                'location' => 'مسقط، عمان',
                'active_role' => 'seller',
            ],
            [
                'name' => 'مصممة أزياء',
                'email' => 'designer@example.com',
                'password' => Hash::make('designerpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'مصممة أزياء متخصصة في تصميم الأزياء التقليدية العربية مع لمسة عصرية',
                'created_at' => '2023-09-25',
                'last_login' => null,
                'phone' => '+20111222333',
                'location' => 'المنصورة، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'فنان تشكيلي',
                'email' => 'artist@example.com',
                'password' => Hash::make('artistpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-09-26',
                'last_login' => null,
                'phone' => '+20111222334',
                'location' => 'أسوان، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'حرفية كروشيه',
                'email' => 'crochet@example.com',
                'password' => Hash::make('crochetpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'created_at' => '2023-09-27',
                'last_login' => null,
                'phone' => '+20111222335',
                'location' => 'طنطا، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'مهندس معماري',
                'email' => 'architect@example.com',
                'password' => Hash::make('architectpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'مهندس معماري متخصص في التصميمات التراثية والمستوحاة من الفن الإسلامي',
                'created_at' => '2023-09-28',
                'last_login' => null,
                'phone' => '+20111222336',
                'location' => 'بورسعيد، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'مصممة اكسسوارات',
                'email' => 'accessories@example.com',
                'password' => Hash::make('accessoriespass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'مصممة اكسسوارات يدوية فريدة مستوحاة من التراث المصري القديم والحديث',
                'created_at' => '2023-09-29',
                'last_login' => null,
                'phone' => '+20111222337',
                'location' => 'الجيزة، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'حرفي متخصص في أعمال الريزن',
                'email' => 'resin.artist@example.com',
                'password' => Hash::make('resinpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'حرفي متخصص في فن الريزن وصناعة قطع فنية وعملية مميزة باستخدام مواد الريزن والأصباغ',
                'created_at' => '2023-09-30',
                'last_login' => null,
                'phone' => '+20111222338',
                'location' => 'الإسماعيلية، مصر',
                'active_role' => 'seller',
            ],
            [
                'name' => 'طاهية متخصصة في المأكولات المصرية',
                'email' => 'chef@example.com',
                'password' => Hash::make('chefpass'),
                'role' => 'seller',
                'avatar' => '',
                'status' => 'active',
                'bio' => 'طاهية محترفة متخصصة في المأكولات المصرية التقليدية والحلويات الشرقية بلمسات عصرية',
                'created_at' => '2023-10-01',
                'last_login' => null,
                'phone' => '+20111222339',
                'location' => 'الزقازيق، مصر',
                'active_role' => 'seller',
            ],
        ];
        foreach ($users as $user) {
            DB::table('users')->insert($user);
        }
    }
}
